<?php
	//以购买产品试图模型wl
	class ServerViewModel extends ViewModel {
		public $viewFields = array(
			'Servive_rec'=>array(
				
			
			),
			'Order'=>array(
				'id'=>'order_id',
				'cusid',
				//'creator',
				'ip',
				'domain',
				//'payment',
				//'ctime'=>'order_ctime',
				//'from'=>'fromtime',
				'to'=>'totime',
				//'note',
				//'status'=>'order_status',
				'_as'=>'o'
				),
			'Cus_info'=>array(
				//'id'=>'cus_id',
				'cusname',
				'contact',
				//'cont_job',
				'mobile',
				'tel',
				'email',
				'address',
				//'id_card',
				//'web',
				'salemanId',
				//'ctime'=>'cus_ctime',
				'custype',
				'_as'=>'c',
				'_on'=>'o.cusid=c.id'
				),
			'Protype'=>array(
				'tid',
				//'parentId',
				'labelname',
				'path',
				'_as'=>'p',
				'_on'=>'o.pid=p.tid'
				),
		);
	}
?>